package views;

import javax.swing.table.DefaultTableModel;


//jmvc.Navigator.view("home");
//       this.setVisible(false);

/**
 *
 * @author Samuel
 */
public class BukuPage extends javax.swing.JFrame {

   private controllers.BukuController bukuController;
   private java.sql.ResultSet dataBuku;
    
    private String kd_buku_hapus;
    /**
     * Creates new form buku
     */
    public BukuPage(controllers.BukuController bukuController) {
        this.bukuController = bukuController;
        dataBuku = bukuController.getBookData();
        
        initComponents();
        
        CBJenis.addItem("PILIH");
        CBJenis.addItem("Novel");
        CBJenis.addItem("Komik");
        CBJenis.addItem("Biografi");
        CBJenis.addItem("Buku Sekolah");
        
        this.setLocationRelativeTo(null);
       
        BHapus.setEnabled(false);
        BUbah.setEnabled(false);
        aktif();
        reset();
    }
    
    void aktif(){
        CBJenis.setEnabled(true);
        
    }
    
    void reset(){
        BHapus.setEnabled(false);
        BUbah.setEnabled(false);
        CBJenis.setSelectedItem("PILIH");
        TFkode.setText("");
        TFTahun.setText("");
        TFStok.setText("");
        TFPenulis.setText("");
        TFPenerbit.setText("");
        TFJudul.setText("");
        TFHargaPokok.setText("");
        TFHargaJual.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TFHargaPokok = new javax.swing.JTextField();
        BUbah = new javax.swing.JButton();
        TFHargaJual = new javax.swing.JTextField();
        BReset = new javax.swing.JButton();
        TFPenerbit = new javax.swing.JTextField();
        TFPenulis = new javax.swing.JTextField();
        CBJenis = new javax.swing.JComboBox<>();
        TFkode = new javax.swing.JTextField();
        TFJudul = new javax.swing.JTextField();
        TFTahun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTambah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TFStok = new javax.swing.JTextField();
        BHapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TFSearch = new javax.swing.JTextField();
        BBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TData = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Harga Jual");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 390, -1, -1));

        TFHargaPokok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFHargaPokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 353, 108, -1));

        BUbah.setText("Ubah");
        BUbah.setAutoscrolls(true);
        BUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });
        getContentPane().add(BUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 73, 30));

        TFHargaJual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 389, 108, -1));

        BReset.setText("Reset");
        BReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        getContentPane().add(BReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 80, 30));

        TFPenerbit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 245, 106, -1));

        TFPenulis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 209, 107, -1));

        CBJenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(CBJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 169, 107, -1));

        TFkode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 97, 107, -1));

        TFJudul.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 133, 107, -1));

        TFTahun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 281, 107, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Kode Buku");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 98, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Judul");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Jenis");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 172, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Penulis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 209, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Penerbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 247, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Tahun");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 282, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Stok");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 318, -1, -1));

        BTambah.setText("Tambah");
        BTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 73, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Harga Pokok");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 354, -1, -1));

        TFStok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(TFStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 317, 108, -1));

        BHapus.setText("Hapus");
        BHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 433, 80, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        TFSearch.setBackground(new java.awt.Color(252, 252, 252));
        TFSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TFSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFSearchKeyPressed(evt);
            }
        });

        BBack.setBackground(new java.awt.Color(153, 51, 255));
        BBack.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BBack.setForeground(new java.awt.Color(255, 255, 255));
        BBack.setText("Kembali");
        BBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackActionPerformed(evt);
            }
        });

        TData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul", "Jenis", "Penulis", "Penerbit", "Tahun", "Stok", "Harga Pokok", "Harga Jual"
            }
        ));
        String[] columns = {"Kode Buku", "Judul", "Jenis", "Penulis", "Penerbit", "Tahun", "Stok", "Harga Pokok", "Harga Jual"};

        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(columns, 0);

        try {
            while ( dataBuku.next() ) {
                String[] data = {
                    dataBuku.getString("kd_buku"),
                    dataBuku.getString("judul"),
                    dataBuku.getString("jenis"),
                    dataBuku.getString("penulis"),
                    dataBuku.getString("penerbit"),
                    dataBuku.getString("tahun"),
                    Integer.toString(dataBuku.getInt("stok")),
                    Integer.toString(dataBuku.getInt("harga_pokok")),
                    Integer.toString(dataBuku.getInt("harga_jual"))
                };

                tableModel.addRow(data);
            }
        } catch ( java.sql.SQLException e ) {
            System.out.println(e);
        }

        TData.setModel(tableModel);
        TData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(BBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(TFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        bukuController.handleAddData();
        jmvc.Navigator.view("buku");
        this.setVisible(false);
    }//GEN-LAST:event_BTambahActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        BTambah.setEnabled(true);
        reset();
        aktif();
        CBJenis.requestFocus();
    }//GEN-LAST:event_BResetActionPerformed

    private void BBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackActionPerformed
        jmvc.Navigator.view("home");
        this.setVisible(false);
    }//GEN-LAST:event_BBackActionPerformed

    private void TDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TDataMouseClicked
        // TODO add your handling code here:
        BTambah.setEnabled(false);
        BHapus.setEnabled(true);
        BUbah.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) TData.getModel();
        int selectedRow = TData.getSelectedRow();
        kd_buku_hapus = model.getValueAt(selectedRow, 0).toString();
        try{
            TFkode.setText(model.getValueAt(selectedRow, 0).toString());
            TFTahun.setText(model.getValueAt(selectedRow, 5).toString());
            TFStok.setText(model.getValueAt(selectedRow, 6).toString());
            String comboSub =model.getValueAt(selectedRow, 2).toString();
            for (int i = 0; i < CBJenis.getItemCount();i++){
                if(CBJenis.getItemAt(i).toString().equalsIgnoreCase(comboSub)) {
                   CBJenis.setSelectedIndex(i);
                }
            }
            TFPenulis.setText(model.getValueAt(selectedRow, 3).toString());
            TFPenerbit.setText(model.getValueAt(selectedRow, 4).toString());
            TFJudul.setText(model.getValueAt(selectedRow, 1).toString());
            TFHargaPokok.setText(model.getValueAt(selectedRow, 7).toString());
            TFHargaJual.setText(model.getValueAt(selectedRow, 8).toString());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_TDataMouseClicked

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        bukuController.handleDeleteData(kd_buku_hapus);
        
    }//GEN-LAST:event_BHapusActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        // TODO add your handling code here:
        if ( bukuController.handleUpdateData(kd_buku_hapus) ) {
            jmvc.Navigator.view("buku");
        }
    }//GEN-LAST:event_BUbahActionPerformed

    private void TFSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            String s = TFSearch.getText();
            
            bukuController.handleSearchData(s);
        }
    }//GEN-LAST:event_TFSearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBack;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton BUbah;
    public javax.swing.JComboBox<String> CBJenis;
    public javax.swing.JTable TData;
    public javax.swing.JTextField TFHargaJual;
    public javax.swing.JTextField TFHargaPokok;
    public javax.swing.JTextField TFJudul;
    public javax.swing.JTextField TFPenerbit;
    public javax.swing.JTextField TFPenulis;
    private javax.swing.JTextField TFSearch;
    public javax.swing.JTextField TFStok;
    public javax.swing.JTextField TFTahun;
    public javax.swing.JTextField TFkode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}