package views;

/**
 *
 * @author kevin + haikalrafifas
 */
public class TransaksiPage extends javax.swing.JFrame {
    private final controllers.TransaksiController controller = controllers.TransaksiController.controller;
    
    public TransaksiPage() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPelanggan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBuku = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tkpes = new javax.swing.JTextField();
        thar = new javax.swing.JTextField();
        tkpel = new javax.swing.JTextField();
        tktrans = new javax.swing.JTextField();
        tjum = new javax.swing.JTextField();
        tkbuk = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabker = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        bsel = new javax.swing.JButton();
        bbat = new javax.swing.JButton();
        ttharga = new javax.swing.JTextField();
        tnpem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btranssel = new javax.swing.JButton();
        bAddToCart = new javax.swing.JButton();
        jBkembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Data Pelanggan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 119, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Data Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 119, -1, -1));

        TPelanggan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Gender", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TPelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, 311, 154));

        TBuku.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul", "Penulis", "Penerbit", "Tahun", "Stok", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBuku);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 144, -1, 154));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Kode Pesan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 349, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Kode Transaksi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 349, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Kode Pelanggan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 415, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Kode Buku");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 415, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 485, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 485, -1, -1));
        getContentPane().add(tkpes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 371, 105, -1));
        getContentPane().add(thar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 507, 105, -1));
        getContentPane().add(tkpel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 451, 105, -1));
        getContentPane().add(tktrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 371, 105, -1));
        getContentPane().add(tjum, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 507, 105, -1));
        getContentPane().add(tkbuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 451, 105, -1));

        tabker.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pesanan", "ID Transaksi", "Nama Pelanggan", "Jumlah", "Sub Total"
            }
        ));
        jScrollPane3.setViewportView(tabker);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 144, 425, 154));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Keranjang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 119, -1, -1));

        bsel.setBackground(new java.awt.Color(0, 51, 102));
        bsel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bsel.setForeground(new java.awt.Color(249, 249, 249));
        bsel.setText("Selesai");
        bsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselActionPerformed(evt);
            }
        });
        getContentPane().add(bsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 341, 91, 37));

        bbat.setBackground(new java.awt.Color(0, 51, 102));
        bbat.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bbat.setForeground(new java.awt.Color(249, 249, 249));
        bbat.setText("Batal");
        bbat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatActionPerformed(evt);
            }
        });
        getContentPane().add(bbat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 341, 104, 37));
        getContentPane().add(ttharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 444, 140, -1));
        getContentPane().add(tnpem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 444, 140, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setText("Total Harga");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 410, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setText("Nama Pembeli");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 410, -1, -1));

        btranssel.setBackground(new java.awt.Color(153, 51, 255));
        btranssel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btranssel.setForeground(new java.awt.Color(249, 249, 249));
        btranssel.setText("Transaksi Selesai");
        btranssel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransselActionPerformed(evt);
            }
        });
        getContentPane().add(btranssel, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 515, 170, 37));

        bAddToCart.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bAddToCart.setText("Tambah ke Keranjang");
        bAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(bAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 552, -1, -1));

        jBkembali.setBackground(new java.awt.Color(153, 51, 255));
        jBkembali.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBkembali.setForeground(new java.awt.Color(249, 249, 249));
        jBkembali.setText("Kembali");
        jBkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jBkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 552, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPelangganMouseClicked
        controller.handleSelectedRowPelanggan();
    }//GEN-LAST:event_TPelangganMouseClicked

    private void bbatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatActionPerformed
        controller.handleDeleteCartData();
    }//GEN-LAST:event_bbatActionPerformed

    private void TBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBukuMouseClicked
        controller.handleSelectedRowBuku();
    }//GEN-LAST:event_TBukuMouseClicked

    private void bAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddToCartActionPerformed
        controller.handleAddCartData();
    }//GEN-LAST:event_bAddToCartActionPerformed

    private void bselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselActionPerformed
        controller.handleCheckout();
    }//GEN-LAST:event_bselActionPerformed

    private void btransselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransselActionPerformed
        controller.handleFinishTransaction();
    }//GEN-LAST:event_btransselActionPerformed

    private void jBkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkembaliActionPerformed
        controller.goToPreviousPage();
    }//GEN-LAST:event_jBkembaliActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TBuku;
    public javax.swing.JTable TPelanggan;
    public javax.swing.JButton bAddToCart;
    private javax.swing.JButton bbat;
    public javax.swing.JButton bsel;
    public javax.swing.JButton btranssel;
    private javax.swing.JButton jBkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tabker;
    public javax.swing.JTextField thar;
    public javax.swing.JTextField tjum;
    public javax.swing.JTextField tkbuk;
    public javax.swing.JTextField tkpel;
    public javax.swing.JTextField tkpes;
    public javax.swing.JTextField tktrans;
    public javax.swing.JTextField tnpem;
    public javax.swing.JTextField ttharga;
    // End of variables declaration//GEN-END:variables
}
